# Generated by Django 4.0.5 on 2022-07-03 09:51

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'о журнале', 'verbose_name_plural': 'о журнале'},
        ),
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ('-publish_date',), 'verbose_name': 'архив', 'verbose_name_plural': 'архив'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'главная страница', 'verbose_name_plural': 'главная страница'},
        ),
        migrations.AlterModelOptions(
            name='informationpage',
            options={'verbose_name': 'страница с информацией', 'verbose_name_plural': 'страница с информацией'},
        ),
        migrations.AlterField(
            model_name='about',
            name='contact',
            field=models.CharField(max_length=300, verbose_name='контакты журнала'),
        ),
        migrations.AlterField(
            model_name='about',
            name='editorial_team',
            field=models.TextField(verbose_name='раздел о редакции'),
        ),
        migrations.AlterField(
            model_name='about',
            name='journal',
            field=models.TextField(verbose_name='раздел о журнале'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='all_issue_pdf',
            field=models.FileField(blank=True, upload_to='issue_pdf/', verbose_name='номер целиком (опционально)'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='article_pdf',
            field=models.FileField(upload_to='issue_pdf/', verbose_name='pdf-файл статьи'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='article_title',
            field=models.CharField(max_length=300, verbose_name='название статьи'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='author',
            field=models.CharField(max_length=200, verbose_name='имя автора'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='journal_template.category', verbose_name='категория (опционально)'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='issue_img',
            field=models.ImageField(blank=True, null=True, upload_to='issue_img/%Y/%m/%d/', verbose_name='фотография номера журнала (опционально)'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='issue_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='заголовок журнала (опционально)'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='publish_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата публикации (автоматически)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='affiliation',
            field=models.CharField(max_length=350, verbose_name='аффилиация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=300, verbose_name='ключевые слова'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(verbose_name='аннотация'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=250, verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='footer_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='цвет футера (опционально)'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='head_img/%Y/%m/%d/', verbose_name='титульная фотография (опционально)'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='title',
            field=models.CharField(max_length=250, verbose_name='название журнала'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='authors',
            field=models.TextField(verbose_name='авторам'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='library',
            field=models.TextField(verbose_name='библиотекам'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='reader',
            field=models.TextField(verbose_name='читателям'),
        ),
    ]
