# Generated by Django 4.0.5 on 2022-07-12 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_template', '0004_article_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_url',
        ),
        migrations.AddField(
            model_name='archive',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journal_template.article', verbose_name='статья'),
        ),
    ]
