# Generated by Django 4.0.5 on 2022-07-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_template', '0008_remove_archive_article_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='archive',
        ),
        migrations.AlterField(
            model_name='archive',
            name='article',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='articles',
                to='journal_template.article',
                verbose_name='статья|автор статьи (необходимо заполнить)',
            ),
        ),
    ]
