# Generated by Django 4.0.5 on 2022-07-19 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal_template', '0010_clientcontact_about_client_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'verbose_name': 'контакт пользователя', 'verbose_name_plural': 'контакты пользователя'},
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата (автоматически)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archive',
            name='publish_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата (автоматически)'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='surname',
            field=models.CharField(max_length=150, verbose_name='фамилия'),
        ),
    ]
