# Generated by Django 4.0.5 on 2022-07-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_template', '0012_alter_archive_publish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='client_contact',
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='massage',
            field=models.TextField(default=1, verbose_name='текст сообещния'),
            preserve_default=False,
        ),
    ]
