# Generated by Django 4.0.5 on 2022-07-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'journal_template',
            '0013_remove_about_client_contact_clientcontact_massage',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='massage',
            field=models.TextField(verbose_name='текст сообщения'),
        ),
    ]
